#! /bin/bash

pi="pi@raspberrypi.local"

ssh $pi 'sudo apt-get update; \
sudo apt-get -y install curl;\
sudo apt-get -y install apache2; \
sudo apt-get install -y libapache2-mod-python'

scp servers/tmp/test $pi:/home/pi
ssh $pi 'sudo chown $USER:$USER $HOME/test; \
sudo chmod 755 $HOME/test; \
sudo cp $HOME/test /usr/lib/cgi-bin'

# /etc/apache2/conf-available/serve-cgi-bin.conf
# has ScriptAlias already set up to /usr/lib/cgi-bin/

echo 'running a2enmod cgi'
ssh $pi 'sudo a2enmod cgi; \
sudo systemctl restart apache2'

echo 'test apache2:'
ssh $pi 'curl localhost/cgi-bin/test'

echo 'disabling apache2 server'
ssh $pi 'sudo update-rc.d apache2 disable' 
